language: c
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install: ./cp.sh
script:
  - build_main_platforms
notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always
